#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es Contents Contenido
::msgcat::mcset es Search Buscar
::msgcat::mcset es More Más
::msgcat::mcset es Text Texto
::msgcat::mcset es Forward Adelante
::msgcat::mcset es Backward Atrás
::msgcat::mcset es {Consider case} Mayusculas/Minúsculas
::msgcat::mcset es {From beginning} {Desde el inicio}
::msgcat::mcset es Home Inicio
::msgcat::mcset es Previus Previo
::msgcat::mcset es Next Siguiente
::msgcat::mcset es {Search in page...} {Buscar en página}
::msgcat::mcset es {Search more} {Buscar más}
::msgcat::mcset es Close Cerrar
