global panneau
set panneau(DlgShift,buttonShift) "0"
set panneau(DlgShift,geometry) "278x182+657+251"
set panneau(DlgShift,position) "+657+251"
set panneau(DlgShift,shiftSpeed) "x5"
set panneau(DlgShift,xShiftDirection) "O"
set panneau(DlgShift,xShiftDirection1) "w"
set panneau(DlgShift,xShiftTime) "2"
set panneau(DlgShift,yShiftDirection) "N"
set panneau(DlgShift,yShiftDirection1) "n"
set panneau(DlgShift,yShiftTime) "2"
