#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset en OK {}
::msgcat::mcset en Close {}
::msgcat::mcset en Cancel {}
::msgcat::mcset en Warning {}
::msgcat::mcset en Ok {}
::msgcat::mcset en {unknown option '%s' in snit_messageBox} {}
::msgcat::mcset en Abort {}
::msgcat::mcset en Retry {}
::msgcat::mcset en Ignore {}
::msgcat::mcset en Yes {}
::msgcat::mcset en No {}
::msgcat::mcset en {unknown type: '%s' in snit_messageBox} {}
::msgcat::mcset en {bad default option: '%s' in snit_messageBox} {}
::msgcat::mcset en Action {}
::msgcat::mcset en {New password} {}
::msgcat::mcset en Uncrypt {}
::msgcat::mcset en {Choose action to perform:} {}
::msgcat::mcset en {Enter password} {}
::msgcat::mcset en Password: {}
::msgcat::mcset en {Enter password to encrypt:} {}
::msgcat::mcset en {Password must have at least 4 characters} {}
::msgcat::mcset en {Change page type} {}
::msgcat::mcset en {Choose a new page type for page '%s'} {}
::msgcat::mcset en {Current type: %s} {}
::msgcat::mcset en {New type:} {}
