#
# Fichier : calaphot.cap
# Mise a jour $Id: calaphot.cap 7092 2011-04-06 16:36:29Z robertdelmas  $
#

#=========================================================================
#   Début de la déclaration des textes localisés (internationalisation)
#=========================================================================

global langage

# Hors version
set calaphot(texte,titre)                  "Calaphot"
set calaphot(texte,copyright)              "(c)2001-$::audace(endCopyright)   O. Thizy & J. Michelet"

# *************** Version anglaise ****************************

set calaphot(texte,titre_menu)             "Light Curves (Calaphot)"
set calaphot(texte,titre_saisie)           "Photometry Script Parameters"
set calaphot(texte,operateur)              "Operator Name"
set calaphot(texte,objet)                  "Object Name"
set calaphot(texte,code_UAI)               "Observatory IUA Code"
set calaphot(texte,source)                 "Generic Name for the Image Files"
set calaphot(texte,indice_premier)         "First Image Index"
set calaphot(texte,nombre_images)          "Number of Images"
set calaphot(texte,niveau_minimal)         "Lower Limit for ADU (floor)"
set calaphot(texte,niveau_maximal)         "Higher Limit for ADU (ceiling)"
set calaphot(texte,o_rayon1)               "Inner Oval Radius (in FWHM)"
set calaphot(texte,o_rayon2)               "Inner Crown Radius (in FWHM)"
set calaphot(texte,o_rayon3)               "Outer Crown Radius (in FWHM)"
set calaphot(texte,sortie)                 "Output Generic File Name"
set calaphot(texte,signal_bruit)           "Minimum S/N Ratio"
set calaphot(texte,mode)                   "Calculation Mode"
set calaphot(texte,mode_ouverture)         "Aperture Photometry"
set calaphot(texte,mode_modelisation)      "Star Modelling"
set calaphot(texte,continuer)              "Go"
set calaphot(texte,annuler)                "Cancel"
set calaphot(texte,o_surechantillonage)    "Pixel Oversampling"
set calaphot(texte,err_indice)             "Error:  last index is smaller or equal to the first one"
set calaphot(texte,verification)           "Check Files %s\[%d...%d\]%s"
set calaphot(texte,err_existence_1)        "The file"
set calaphot(texte,err_existence_2)        "does not exist"
set calaphot(texte,mag_superetoile)        "Magnitude of the Super Star"
set calaphot(texte,vitesse_asteroide)      "Asteroid Speed (pixel/day)"
set calaphot(texte,image_rejetee)          "Rejected Image"
set calaphot(texte,etoile)                 "Star"
set calaphot(texte,asteroide)              "Asteroid"
set calaphot(texte,moyenne)                "Average"
set calaphot(texte,ecart_type)             "Standard Deviation"
set calaphot(texte,type_images)            "Image Type"
set calaphot(texte,type_images_0)          "Not Registered"
set calaphot(texte,type_images_1)          "Registered"
set calaphot(texte,format_sortie)          "Data Format"
set calaphot(texte,format_sortie_0)        "CDR"
set calaphot(texte,format_sortie_1)        "Canopus"
set calaphot(texte,affichage)              "Calculation Display"
set calaphot(texte,affichage_0)            "Minimum"
set calaphot(texte,affichage_1)            "Normal"
set calaphot(texte,affichage_2)            "Maximum"
set calaphot(texte,date_images)            "Image Date"
set calaphot(texte,date_images_0)          "Start of Exposure"
set calaphot(texte,date_images_1)          "Center of Exposure"
set calaphot(texte,param_ouverture)        "Parameters for the Aperture Mode"
set calaphot(texte,param_modelisation)     "Parameters for the Modelling Mode"
set calaphot(texte,param_generaux)         "General Settings"
set calaphot(texte,recapitulation)         "Summary"
set calaphot(texte,heure_debut)            "Start at:"
set calaphot(texte,heure_fin)              "End at:"
set calaphot(texte,fin_normale)            "----------Normal End of Script----------"
set calaphot(texte,fin_anticipee)          "----------Abnormal End of Script---------"
set calaphot(texte,validation_etoile)      "Adding a Star"
set calaphot(texte,devalidation_etoile)    "Removing a Star"
set calaphot(texte,continuation)           "Next"
set calaphot(texte,annulation)             "Stop"
set calaphot(texte,etoile_reference)       "Reference Star"
set calaphot(texte,etoile_a_supprimer)     "Star to REMOVE"
set calaphot(texte,magnitude)              "Magnitude"
set calaphot(texte,valider)                "OK"
set calaphot(texte,pas_etoile)             "No reference star selected!"
set calaphot(texte,pas_asteroide)          "No asteroid selected on both images!"
set calaphot(texte,probleme)               "Problem"
set calaphot(texte,pos_aster_1)            "Pos. in First Image"
set calaphot(texte,pos_aster_2)            "Pos. in Last Image"
set calaphot(texte,etoile_inconnue)        "Unknown Star"
set calaphot(texte,etoile_prise)           "Star Alrealy Selected"
set calaphot(texte,retour)                 "Back"
set calaphot(texte,calcul_ellipses)        "Ellipse Calculation from Star Profile"
set calaphot(texte,banniere_CDR_1)         "Data Processed by CalaPhot"
set calaphot(texte,banniere_CDR_2)         "under AudeLA"
set calaphot(texte,et_indesirables)        "Star to Remove"
set calaphot(texte,pose_minute)            "Exposure Duration in"
set calaphot(texte,pose_minute_0)          "Seconds"
set calaphot(texte,pose_minute_1)          "Minutes"
set calaphot(texte,constante_mag)          "Magnitudes Const."
set calaphot(texte,mauvaise_version)       "Bad Version of libjm Library"
set calaphot(texte,jour_julien)            "Julian Day"
set calaphot(texte,gain_camera)            "Camera Gain (e-/ADU)"
set calaphot(texte,pas_etoile_ind)         "No Star to Remove"
set calaphot(texte,bruit_lecture)          "Readout Noise (e-)"
set calaphot(texte,arret)                  "Stop"
set calaphot(texte,fichier_cl)             "Name of Resulting PostScript File"
set calaphot(texte,rien_a_voir)            "No Light Curve"
set calaphot(texte,tri_images)             "Sorting by Date of Images"
set calaphot(texte,type_capteur)           "CCD Model"
set calaphot(texte,type_telescope)         "Telescope Type"
set calaphot(texte,diametre_telescope)     "Telescope Aperture (m)"
set calaphot(texte,focale_telescope)       "Telescope Focal Length (m)"
set calaphot(texte,catalogue_reference)    "Reference Catalog"
set calaphot(texte,champ1)                 "The field "
set calaphot(texte,champ2)                 " must contain a value"
set calaphot(texte,filtre_optique)         "Optical Filter"
set calaphot(texte,suivant)                "Next"
set calaphot(texte,s_saturation)           "Saturation level (ADU)"
set calaphot(texte,mode_sextractor)        "Using Sextractor"
set calaphot(texte,non)                    "No"
set calaphot(texte,oui)                    "Yes"
set calaphot(texte,reprise_astres)         "Using the previously selected objects"
set calaphot(texte,reprise_astres_0)       $calaphot(texte,non)
set calaphot(texte,reprise_astres_1)       $calaphot(texte,oui)
set calaphot(texte,param_sextractor)       "Parameters for the Sextractor Mode"
set calaphot(texte,tri_images_0)           $calaphot(texte,non)
set calaphot(texte,tri_images_1)           $calaphot(texte,oui)
set calaphot(texte,detection_ini)          "The Calaphot version has changed: The calaphot.ini settings will be reset.The previous file has been renamed as calaphot.ini.old"
set calaphot(texte,aide)                   "Help"
set calaphot(texte,pas_image_valide)       "No valid image. You should check the minimum S/N ratio."
set calaphot(texte,image)                  "Image"
set calaphot(texte,temps_pose_nul)         "Void exposure duration"
set calaphot(texte,mag_relative)           "Relative Magnitude"
set calaphot(texte,err_modelisation)       "Error in fitting"
set calaphot(texte,plus_jeune)             " is older than the previous one"
set calaphot(texte,implication_defoc)      "The processing of very defocused images implies Aperture Photometry."
set calaphot(texte,defocalisation)         "Very defocused images"
set calaphot(texte,defocalisation_0)       $calaphot(texte,non)
set calaphot(texte,defocalisation_1)       $calaphot(texte,oui)
set calaphot(texte,aucune_valide)          "Not any valid image"
set calaphot(texte,trop_peu_image)         "The number of images to process is smaller than 2"
set calaphot(texte,trop_peu_image_2)       "The number of images to process is smaller than specified"
set calaphot(texte,liste_image)            "Image list : "
set calaphot(texte,liste_vide)             "No image named as "
set calaphot(texte,question_continuer)     "Do you to continue ?"
set calaphot(texte,nombre_variables)         "Number of variable stars"
set calaphot(texte,variable)                 "Variable"
set calaphot(texte,nombre_references)        "Number of reference stars"
set calaphot(texte,reference)                "Reference"
set calaphot(texte,reference_sans_accent)    "Reference"
set calaphot(texte,nom_gardes_faible)        "Too few selected images"
set calaphot(texte,titre_selection_finale)   "Selection of images"
set calaphot(texte,etape)                    "Erreur at step "


# *************** Version française ***************************
if { [ string compare $langage "french" ] == "0" } {
    set calaphot(texte,titre_menu)                  "Courbes de lumière (Calaphot)"
    set calaphot(texte,titre_saisie)                "Paramètres du script de photométrie"
    set calaphot(texte,operateur)                   "Nom de l'opérateur"
    set calaphot(texte,objet)                       "Nom de l'objet"
    set calaphot(texte,code_UAI)                    "Code UAI de l'observatoire"
    set calaphot(texte,source)                      "Nom générique des images"
    set calaphot(texte,indice_premier)              "Indice de la première image"
    set calaphot(texte,nombre_images)               "Nombre d'images"
    set calaphot(texte,o_rayon1)                    "Rayon de l'ovale intérieur (en FWHM)"
    set calaphot(texte,o_rayon2)                    "Rayon interne de la couronne (en FWHM)"
    set calaphot(texte,o_rayon3)                    "Rayon externe de la couronne (en FWHM)"
    set calaphot(texte,sortie)                      "Nom générique des fichiers résultat"
    set calaphot(texte,signal_bruit)                "Rapport S/B limite"
    set calaphot(texte,mode)                        "Mode de calcul"
    set calaphot(texte,mode_ouverture)              "Phot. d'ouverture"
    set calaphot(texte,mode_modelisation)           "Modélisation d'étoiles"
    set calaphot(texte,continuer)                   "Continuer"
    set calaphot(texte,annuler)                     "Annuler"
    set calaphot(texte,o_surechantillonage)         "Facteur de division des pixels"
    set calaphot(texte,err_indice)                  "Erreur : Dernier indice inférieur ou égal au premier"
    set calaphot(texte,verification)                "Vérification des fichiers %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)             "Le fichier"
    set calaphot(texte,err_existence_2)             "n'existe pas"
    set calaphot(texte,mag_superetoile)             "Magnitude de la super-étoile"
    set calaphot(texte,vitesse_asteroide)           "Vitesse de l'astéroïde (pixel/jour)"
    set calaphot(texte,image_rejetee)               "Image rejetée"
    set calaphot(texte,etoile)                      "Etoile"
    set calaphot(texte,asteroide)                   "Asteroïde"
    set calaphot(texte,moyenne)                     "Moyenne"
    set calaphot(texte,ecart_type)                  "Ecart-type"
    set calaphot(texte,type_images)                 "Type des images"
    set calaphot(texte,type_images_0)               "Non recalées"
    set calaphot(texte,type_images_1)               "Recalées"
    set calaphot(texte,format_sortie)               "Format des données"
    set calaphot(texte,format_sortie_0)             "CDR"
    set calaphot(texte,format_sortie_1)             "Canopus"
    set calaphot(texte,affichage)                   "Affichage des calculs"
    set calaphot(texte,affichage_0)                 "Minimal"
    set calaphot(texte,affichage_1)                 "Normal"
    set calaphot(texte,affichage_2)                 "Maximal"
    set calaphot(texte,date_images)                 "Date des images"
    set calaphot(texte,date_images_0)               "Début de pose"
    set calaphot(texte,date_images_1)               "Milieu de pose"
    set calaphot(texte,param_ouverture)             "Paramètres pour le mode ouverture"
    set calaphot(texte,param_modelisation)          "Paramètres pour le mode modélisation"
    set calaphot(texte,param_generaux)              "Paramètres généraux"
    set calaphot(texte,recapitulation)              "Récapitulation des paramètres"
    set calaphot(texte,heure_debut)                 "Début à :"
    set calaphot(texte,heure_fin)                   "Fin à :"
    set calaphot(texte,fin_normale)                 "----------Fin normale du script----------"
    set calaphot(texte,fin_anticipee)               "---------Fin anticipée du script---------"
    set calaphot(texte,validation_etoile)           "Ajout d'une étoile"
    set calaphot(texte,devalidation_etoile)         "Retrait d'une étoile"
    set calaphot(texte,continuation)                "Suite du script"
    set calaphot(texte,annulation)                  "Arrêt du script"
    set calaphot(texte,etoile_reference)            "Etoile de référence"
    set calaphot(texte,etoile_a_supprimer)          "Etoile à SUPPRIMER"
    set calaphot(texte,magnitude)                   "Magnitude"
    set calaphot(texte,valider)                     "Valider"
    set calaphot(texte,pas_etoile)                  "Vous n'avez pas sélectionné d'étoiles de références!!"
    set calaphot(texte,pas_asteroide)               "Vous n'avez pas sélectionné l'astéroïde sur les deux images!!"
    set calaphot(texte,probleme)                    "Problème"
    set calaphot(texte,pos_aster_1)                 "Pos. dans première image"
    set calaphot(texte,pos_aster_2)                 "Pos. dans dernière image"
    set calaphot(texte,etoile_inconnue)             "Etoile inconnue"
    set calaphot(texte,etoile_prise)                "Etoile déjà sélectionnée"
    set calaphot(texte,retour)                      "Retour"
    set calaphot(texte,calcul_ellipses)             "Calcul des ellipses à partir du profil de l'étoile"
    set calaphot(texte,banniere_CDR_1)              "Données traitées par CalaPhot"
    set calaphot(texte,banniere_CDR_2)              "sous AudeLA"
    set calaphot(texte,et_indesirables)             "Etoiles à supprimer"
    set calaphot(texte,pose_minute)                 "Durée de la pose en"
    set calaphot(texte,pose_minute_0)               "Secondes"
    set calaphot(texte,pose_minute_1)               "Minutes"
    set calaphot(texte,constante_mag)               "Const. magnitudes"
    set calaphot(texte,mauvaise_version)            "Mauvaise version de la librairie libjm"
    set calaphot(texte,jour_julien)                 "Jour Julien"
    set calaphot(texte,gain_camera)                 "Gain de la caméra (e-/pas codeur)"
    set calaphot(texte,pas_etoile_ind)              "Pas d'étoile à supprimer"
    set calaphot(texte,bruit_lecture)               "Bruit de lecture (e-)"
    set calaphot(texte,arret)                       "Arrêt"
    set calaphot(texte,fichier_cl)                  "Nom du fichier PostScript résultat"
    set calaphot(texte,rien_a_voir)                 "Pas de courbe de lumière à montrer"
    set calaphot(texte,tri_images)                  "Tri des images par date croissante"
    set calaphot(texte,type_capteur)                "Type du capteur"
    set calaphot(texte,type_telescope)              "Type du telescope"
    set calaphot(texte,diametre_telescope)          "Diamètre du télescope (m)"
    set calaphot(texte,focale_telescope)            "Focale du télescope (m)"
    set calaphot(texte,catalogue_reference)         "Catalogue de référence"
    set calaphot(texte,champ1)                      "Le champ "
    set calaphot(texte,champ2)                      " doit être saisi"
    set calaphot(texte,filtre_optique)              "Filtre optique"
    set calaphot(texte,suivant)                     "Suivant"
    set calaphot(texte,s_saturation)                "Niveau de saturation (en ADU)"
    set calaphot(texte,mode_sextractor)             "Via Sextractor"
    set calaphot(texte,non)                         "Non"
    set calaphot(texte,oui)                         "Oui"
    set calaphot(texte,reprise_astres)              "Reprise des objets déjà saisis"
    set calaphot(texte,reprise_astres_0)            $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)            $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)            "Paramètres pour le mode Sextractor"
    set calaphot(texte,tri_images_0)                $calaphot(texte,non)
    set calaphot(texte,tri_images_1)                $calaphot(texte,oui)
    set calaphot(texte,detection_ini)               "Changement de version de Calaphot : Le contenu de calaphot.ini va être re-initialisé.L'ancien fichier a été renommé calaphot.ini.old"
    set calaphot(texte,aide)                        "Aide"
    set calaphot(texte,pas_image_valide)            "Aucune image n'est valide. Vérifiez le rapport S/B limite."
    set calaphot(texte,image)                       "Image"
    set calaphot(texte,temps_pose_nul)              "Temps de pose nul"
    set calaphot(texte,mag_relative)                "Magnitude relative"
    set calaphot(texte,err_modelisation)            "Erreur de modélisation"
    set calaphot(texte,plus_jeune)                  " est plus ancienne que la précédente"
    set calaphot(texte,implication_defoc)           "Le traitement des images très défocalisées n'est possible qu'en photométrie d'ouverture."
    set calaphot(texte,defocalisation)              "Images très défocalisées"
    set calaphot(texte,defocalisation_0)            $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)            $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)               "Aucune image n'est valide"
    set calaphot(texte,niveau_minimal)              "Niveau de gris minimal (plancher)"
    set calaphot(texte,niveau_maximal)              "Niveau de gris maximal (saturation)"
    set calaphot(texte,trop_peu_image)              "Le nombre d'images à traiter doit être au moins de 2"
    set calaphot(texte,trop_peu_image_2)            "Le nombre d'images à traiter est inférieur au nombre souhaité"
    set calaphot(texte,liste_image)                 "Liste des images : "
    set calaphot(texte,liste_vide)                  "Aucune image dont le nom soit"
    set calaphot(texte,question_continuer)          "Voulez-vous continuer ?"
    set calaphot(texte,nombre_variables)            "Nombre de variables"
    set calaphot(texte,variable)                    "Variable"
    set calaphot(texte,nombre_references)           "Nombre de références"
    set calaphot(texte,reference)                   "Référence"
    set calaphot(texte,reference_sans_accent)       "Reference"
    set calaphot(texte,nom_gardes_faible)           "Trop peu d'images gardées"
    set calaphot(texte,titre_selection_finale)      "Sélection des images à garder"
    set calaphot(texte,etape)                       "Erreur à l'étape "
    # La fonctionnalité du catalogue automatique n'est plus incluse dans cette version de Calaphot
    # Le fichier calaphot_catalogues.tcl est enlevé du code.
    # set calaphot(texte,champ_trop_large)            "Le champ de l'image est trop large"
    # set calaphot(texte,manuel)                      "Etoiles de référence définies manuellement."
    # set calaphot(texte,auto_local)                  "Etoiles de référence définies à partir d'un catalogue local."
    # set calaphot(texte,auto_internet)               "Etoiles de référence définies à partir d'un catalogue via internet."
    # set calaphot(texte,choix_selection_ref)         "Mode de sélection des étoiles de référence"
    # set calaphot(texte,usnoa2)                      "Catalogue USNO-A2"
    # set calaphot(texte,usnob1)                      "Catalogue USNO-B1"
    # set calaphot(texte,ucac3)                       "Catalogue UCAC-3"
    # set calaphot(texte,nomad1)                      "Catalogue NOMAD1"
    # set calaphot(texte,loneos)                      "Catalogue LONEOS."
    # set calaphot(texte,temps_attente_chargement)    "Durée prévue du téléchargement : "
    # set calaphot(texte,patience)                    "Veuillez patienter..."
    # set calaphot(texte,err_reseau)                  "Le programme n'a pas pu récupérer le catalogue.\nC'est peut-être du à un problème de réseau."
    # set calaphot(texte,err_champ_catalogue)         "Le catalogue téléchargé ne contient pas tous les champs nécessaires"
    # set calaphot(texte,aide_selection_reference)    "Veuillez sélectionner une ou plusieurs étoiles de référence."
    # set calaphot(texte,nom_catalogue)               "Nom"
    # set calaphot(texte,mag_r)                       "Mag. R"
    # set calaphot(texte,mag_b)                       "Mag. B"
    # set calaphot(texte,numero)                      "Numéro"
    # set calaphot(texte,err_pas_de_ref)              "Aucune étoile de référence n'a pu être trouvée"
    # set calaphot(texte,mag_b_r)                     "Indice de couleur B-R"

# *************** Version italienne ***************************
} elseif { [ string compare $langage "italian" ] == "0" } {

    set calaphot(texte,titre_menu)          "Curve di luce (Calaphot)"
    set calaphot(texte,titre_saisie)        "Parametri dello script di fotometria"
    set calaphot(texte,operateur)           "Nome dell'operatore"
    set calaphot(texte,objet)               "Nome oggetto"
    set calaphot(texte,code_UAI)            "Codice IUA dell'osservatorio"
    set calaphot(texte,source)              "Nome generico delle immagini"
    set calaphot(texte,indice_premier)      "Indice della prima immagine"
    set calaphot(texte,nombre_images)       "Numero di immagini"
    set calaphot(texte,o_rayon1)            "Raggio del cerchio interno (in FWHM)"
    set calaphot(texte,o_rayon2)            "Raggio del cerchio centrale (in FWHM)"
    set calaphot(texte,o_rayon3)            "Raggio del cerchio esterno (in FWHM)"
    set calaphot(texte,sortie)              "Nome file di log"
    set calaphot(texte,signal_bruit)        "Rapporto S/N limite"
    set calaphot(texte,mode)                "Modalita' di calcolo"
    set calaphot(texte,mode_ouverture)      "Apertura fotometrica"
    set calaphot(texte,mode_modelisation)   "Modellazione stellare"
    set calaphot(texte,continuer)           "Continuare"
    set calaphot(texte,annuler)             "Annullare"
    set calaphot(texte,o_surechantillonage) "Fattore di divisione dei pixel"
    set calaphot(texte,err_indice)          "Errore: ultimo indice inferiore o uguale al primo"
    set calaphot(texte,verification)        "Verifica di file %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "Il file"
    set calaphot(texte,err_existence_2)     "non esiste"
    set calaphot(texte,mag_superetoile)     "Magnitudine della super-stella"
    set calaphot(texte,vitesse_asteroide)   "Velocita' dell'asteroide (pixel/giorno)"
    set calaphot(texte,image_rejetee)       "Immagine non accettata"
    set calaphot(texte,etoile)              "Stella"
    set calaphot(texte,asteroide)           "Asteroide"
    set calaphot(texte,moyenne)             "Mediana"
    set calaphot(texte,ecart_type)          "Deviazione standard"
    set calaphot(texte,type_images)         "Tipo delle immagini"
    set calaphot(texte,type_images_0)       "Non registrata"
    set calaphot(texte,type_images_1)       "Registrata"
    set calaphot(texte,format_sortie)       "Formato dei dati"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopo"
    set calaphot(texte,affichage)           "Visualizzazione calcoli"
    set calaphot(texte,affichage_0)         "Minimo"
    set calaphot(texte,affichage_1)         "Normale"
    set calaphot(texte,affichage_2)         "Massimo"
    set calaphot(texte,date_images)         "Data delle immagini"
    set calaphot(texte,date_images_0)       "Inizio della posa"
    set calaphot(texte,date_images_1)       "Meta' posa"
    set calaphot(texte,param_ouverture)     "Parametri per la modalita' di apertura"
    set calaphot(texte,param_modelisation)  "Parametri per la modalita' di modellizzazione"
    set calaphot(texte,param_generaux)      "Parametri generali"
    set calaphot(texte,recapitulation)      "Sommario parametri"
    set calaphot(texte,heure_debut)         "Inizio:"
    set calaphot(texte,heure_fin)           "Fine:"
    set calaphot(texte,fin_normale)         "----------Fine normale dello script----------"
    set calaphot(texte,fin_anticipee)       "---------Fine anticipata dello script---------"
    set calaphot(texte,validation_etoile)   "Aggiunta di una stella"
    set calaphot(texte,devalidation_etoile) "Rimozione di una stella"
    set calaphot(texte,continuation)        "Prossimo"
    set calaphot(texte,annulation)          "Stop"
    set calaphot(texte,etoile_reference)    "Stella di riferimento"
    set calaphot(texte,etoile_a_supprimer)  "Stella da ELIMINARE"
    set calaphot(texte,magnitude)           "Magnitudine"
    set calaphot(texte,valider)             "Confermare"
    set calaphot(texte,pas_etoile)          "Non sono state selezionate stelle di riferimento!!"
    set calaphot(texte,pas_asteroide)       "Non e' stato selezionato l'asteroide sulle due immagini!!"
    set calaphot(texte,probleme)            "Problema"
    set calaphot(texte,pos_aster_1)         "Pos. nella prima immagine"
    set calaphot(texte,pos_aster_2)         "Pos. nell'ultima immagine"
    set calaphot(texte,etoile_inconnue)     "Stella sconosciuta"
    set calaphot(texte,etoile_prise)        "Stella gia' selezionata"
    set calaphot(texte,retour)              "Indietro"
    set calaphot(texte,calcul_ellipses)     "Calcolo delle ellissi partendo dal profilo stellare"
    set calaphot(texte,banniere_CDR_1)      "Dati elaborati da CalaPhot"
    set calaphot(texte,banniere_CDR_2)      "in AudeLA"
    set calaphot(texte,et_indesirables)     "Stelle da eliminare"
    set calaphot(texte,pose_minute)         "Durata della posa in"
    set calaphot(texte,pose_minute_0)       "Secondi"
    set calaphot(texte,pose_minute_1)       "Minuti"
    set calaphot(texte,constante_mag)       "Costante magnit."
    set calaphot(texte,mauvaise_version)    "Versione della libreria libjm non valida"
    set calaphot(texte,jour_julien)         "Giorno Giuliano"
    set calaphot(texte,gain_camera)         "Gain della camera (e-/ADU)"
    set calaphot(texte,pas_etoile_ind)      "Nessuna stella da sopprimere"
    set calaphot(texte,bruit_lecture)       "Rumore di lettura (e-)"
    set calaphot(texte,arret)               "Ferma"
    set calaphot(texte,fichier_cl)          "Nome del file PostScript risultato"
    set calaphot(texte,rien_a_voir)         "Nessuna curva di luce da mostrare"
    set calaphot(texte,tri_images)          "Selezione immagini per data"
    set calaphot(texte,type_capteur)        "Modello CCD"
    set calaphot(texte,type_telescope)      "Tipo di telescopio"
    set calaphot(texte,diametre_telescope)  "Diametro telescopio (m)"
    set calaphot(texte,focale_telescope)    "Lunghezza focale telescopio (m)"
    set calaphot(texte,catalogue_reference) "Catalogo di riferimento"
    set calaphot(texte,champ1)              "Il campo "
    set calaphot(texte,champ2)              " deve contenere un valore"
    set calaphot(texte,filtre_optique)      "Filtro ottico"
    set calaphot(texte,suivant)             "Seguente"
    set calaphot(texte,s_saturation)        "Livello di saturazione (ADU)"
    set calaphot(texte,mode_sextractor)     "Via Sextractor"
    set calaphot(texte,non)                 "No"
    set calaphot(texte,oui)                 "Si"
    set calaphot(texte,reprise_astres)      "Uso degli oggetti precedentemente selezionati"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Parametri per il modo Sextractor"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "Cambiamento di versione di Calaphot: Il contenuto di calaphot.ini dovrà essere reinizializzato."
    set calaphot(texte,aide)                "Aiuto"
    set calaphot(texte,pas_image_valide)    "Nessuna immagine valida. Verificare il rapporto S/N minimo."
    set calaphot(texte,image)               "Immagine"
    set calaphot(texte,temps_pose_nul)      "Tempo do posa nulla"
    set calaphot(texte,mag_relative)        "Magnitudine relativa"
    set calaphot(texte,err_modelisation)    "Errore di modellizzazione"
    set calaphot(texte,plus_jeune)          " è più vecchio del precedente"
    set calaphot(texte,implication_defoc)   "Il trattamento delle immagini molto sfocate non è possibile che in fotometria d'apertura."
    set calaphot(texte,defocalisation)      "Immagini molto sfocate"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Alcune immagini non valide"
    set calaphot(texte,niveau_minimal)          "####Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "####Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "###The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "###Image list : "
    set calaphot(texte,liste_vide)              "###No image named as "
    set calaphot(texte,trop_peu_image_2)        "###The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "###Do you to continue ?"
    set calaphot(texte,nombre_variables)        "###Number of variable stars"
    set calaphot(texte,variable)                "###Variable"
    set calaphot(texte,nombre_references)       "###Number of reference stars"
    set calaphot(texte,reference)               "###Reference"
    set calaphot(texte,reference_sans_accent)   "###Reference"
    set calaphot(texte,nom_gardes_faible)       "###Too few selected images"
    set calaphot(texte,titre_selection_finale)  "###Selection of images"
    set calaphot(texte,etape)                   "###Erreur at step "

# *************** Version espagnole ***************************
} elseif { [ string compare $langage "spanish" ] == "0" } {

    set calaphot(texte,titre_menu)          "Curvas de luz (Calaphot)"
    set calaphot(texte,titre_saisie)        "Parámetros del script de fotometría"
    set calaphot(texte,operateur)           "Nombre del operador"
    set calaphot(texte,objet)               "Nombre del objecto"
    set calaphot(texte,code_UAI)            "Código IUA del observatorio"
    set calaphot(texte,source)              "Nombre genérico de ficheros de imagen"
    set calaphot(texte,indice_premier)      "Indice de la primera imagen"
    set calaphot(texte,nombre_images)       "!!!Number of images"
    set calaphot(texte,o_rayon1)            "Radio del círculo interior (en FWHM)"
    set calaphot(texte,o_rayon2)            "Radio del círculo central (en FWHM)"
    set calaphot(texte,o_rayon3)            "Radio del círculo exterior (en FWHM)"
    set calaphot(texte,sortie)              "Nombre del fichero de salida"
    set calaphot(texte,signal_bruit)        "Relación S/N límite"
    set calaphot(texte,mode)                "Modo de cálculo"
    set calaphot(texte,mode_ouverture)      "Fot. de apertura"
    set calaphot(texte,mode_modelisation)   "Modelización de estrellas"
    set calaphot(texte,continuer)           "Continuar"
    set calaphot(texte,annuler)             "Cancelar"
    set calaphot(texte,o_surechantillonage) "Factor de división de pixels"
    set calaphot(texte,err_indice)          "Error: último índice inferior o igual al primero"
    set calaphot(texte,verification)        "Verificación de ficheros %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "El fichero"
    set calaphot(texte,err_existence_2)     "no existe"
    set calaphot(texte,mag_superetoile)     "Magnitud de la super-estrella"
    set calaphot(texte,vitesse_asteroide)   "Velocidad del asteroide (pixel/día)"
    set calaphot(texte,image_rejetee)       "Imagen rechazada"
    set calaphot(texte,etoile)              "Estrella"
    set calaphot(texte,asteroide)           "Asteroide"
    set calaphot(texte,moyenne)             "Media"
    set calaphot(texte,ecart_type)          "Desviación estandard"
    set calaphot(texte,type_images)         "Tipo de imagen"
    set calaphot(texte,type_images_0)       "No registrada"
    set calaphot(texte,type_images_1)       "Registrada"
    set calaphot(texte,format_sortie)       "Formato de datos"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopus"
    set calaphot(texte,affichage)           "Presentación de cálculos"
    set calaphot(texte,affichage_0)         "Mínimo"
    set calaphot(texte,affichage_1)         "Normal"
    set calaphot(texte,affichage_2)         "Máximo"
    set calaphot(texte,date_images)         "Fecha de imágenes"
    set calaphot(texte,date_images_0)       "Comienzo de la exposición"
    set calaphot(texte,date_images_1)       "Centro de la exposición"
    set calaphot(texte,param_ouverture)     "Parámetros para el modo de apertura"
    set calaphot(texte,param_modelisation)  "Parámetros para el modo de modelización"
    set calaphot(texte,param_generaux)      "Parámetros generales"
    set calaphot(texte,recapitulation)      "Resumen de parámetros"
    set calaphot(texte,heure_debut)         "Comenzar en:"
    set calaphot(texte,heure_fin)           "Fin en:"
    set calaphot(texte,fin_normale)         "----------Fin normal del script----------"
    set calaphot(texte,fin_anticipee)       "----------Fin anormal del script---------"
    set calaphot(texte,validation_etoile)   "Añadir una estrella"
    set calaphot(texte,devalidation_etoile) "Quitar una estrella"
    set calaphot(texte,continuation)        "Siguiente"
    set calaphot(texte,annulation)          "Stop"
    set calaphot(texte,etoile_reference)    "Estrella de referencia"
    set calaphot(texte,etoile_a_supprimer)  "Estrellas a QUITAR"
    set calaphot(texte,magnitude)           "Magnitud"
    set calaphot(texte,valider)             "Aceptar"
    set calaphot(texte,pas_etoile)          "No hay estrellas de referencia seleccionadas!"
    set calaphot(texte,pas_asteroide)       "El asteroide no está seleccionado en las dos imágenes!"
    set calaphot(texte,probleme)            "Problema"
    set calaphot(texte,pos_aster_1)         "Pos. en la primera imagen"
    set calaphot(texte,pos_aster_2)         "Pos. en la última imagen"
    set calaphot(texte,etoile_inconnue)     "Estrella desconocida"
    set calaphot(texte,etoile_prise)        "Estrella ya seleccionada"
    set calaphot(texte,retour)              "Atrás"
    set calaphot(texte,calcul_ellipses)     "Cálculo de elipses a partir del perfil de la estrella"
    set calaphot(texte,banniere_CDR_1)      "Datosprocesados por CalaPhot"
    set calaphot(texte,banniere_CDR_2)      "bajo AudeLA"
    set calaphot(texte,et_indesirables)     "Estrellas a quitar"
    set calaphot(texte,pose_minute)         "Duración de la exposición en"
    set calaphot(texte,pose_minute_0)       "Segundos"
    set calaphot(texte,pose_minute_1)       "Minutos"
    set calaphot(texte,constante_mag)       "Const. de magnitudes"
    set calaphot(texte,mauvaise_version)    "Versión erronea de la librería libjm"
    set calaphot(texte,jour_julien)         "Día Juliano"
    set calaphot(texte,gain_camera)         "Ganancia de la cámara (e-/ADU)"
    set calaphot(texte,pas_etoile_ind)      "No hay estrelas que quitar"
    set calaphot(texte,bruit_lecture)       "Ruido de lectura (e-)"
    set calaphot(texte,arret)               "Parar"
    set calaphot(texte,fichier_cl)          "Nombre del fichero PostScript resultado"
    set calaphot(texte,rien_a_voir)         "No existe curva de luz"
    set calaphot(texte,tri_images)          "Ordenado por fecha de las imagenes"
    set calaphot(texte,type_capteur)        "Tipo de CCD"
    set calaphot(texte,type_telescope)      "Tipo de telescopio"
    set calaphot(texte,diametre_telescope)  "Diametro del telescopio (m)"
    set calaphot(texte,focale_telescope)    "Distancia focal del telescopio (m)"
    set calaphot(texte,catalogue_reference) "Catálogo de referencia"
    set calaphot(texte,champ1)              "El campo "
    set calaphot(texte,champ2)              " debe contener un valor"
    set calaphot(texte,filtre_optique)      "Filtro óptico"
    set calaphot(texte,suivant)             "Siguiente"
    set calaphot(texte,s_saturation)        "Nivel de saturación (en ADU)"
    set calaphot(texte,mode_sextractor)     "Via Sextractor"
    set calaphot(texte,non)                 "No"
    set calaphot(texte,oui)                 "Si"
    set calaphot(texte,reprise_astres)      "Usando objetos ya seleccionados"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Parámetros para el modo Sextractor"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "Cambio de la versión de Calaphot: El contenido de calaphot.ini será reinicializado."
    set calaphot(texte,aide)                "Ayuda"
    set calaphot(texte,pas_image_valide)    "Imagen no valida. Verificar el limite S/R."
    set calaphot(texte,image)               "Imagen"
    set calaphot(texte,temps_pose_nul)      "Tiempo de exposición nulo"
    set calaphot(texte,mag_relative)        "Magnitud relativa"
    set calaphot(texte,err_modelisation)    "Error de ajuste"
    set calaphot(texte,plus_jeune)          " es más antigua que la precedente"
    set calaphot(texte,implication_defoc)   "El procesado de imágenes muy desenfocadas solo es posible con fotometría de apertura."
    set calaphot(texte,defocalisation)      "Imágenes muy desenfocadas"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Ninguna imagen validad"
    set calaphot(texte,niveau_minimal)          "####Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "####Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "###The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "###Image list : "
    set calaphot(texte,liste_vide)              "###No image named as "
    set calaphot(texte,trop_peu_image_2)        "###The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "###Do you to continue ?"
    set calaphot(texte,nombre_variables)        "###Number of variable stars"
    set calaphot(texte,variable)                "###Variable"
    set calaphot(texte,nombre_references)       "###Number of reference stars"
    set calaphot(texte,reference)               "###Reference"
    set calaphot(texte,reference_sans_accent)   "###Reference"
    set calaphot(texte,nom_gardes_faible)       "###Too few selected images"
    set calaphot(texte,titre_selection_finale)  "###Selection of images"
    set calaphot(texte,etape)                   "###Erreur at step "

# *************** Version allemande ***************************
} elseif { [ string compare $langage "german" ] == "0" } {

    set calaphot(texte,titre_menu)          "Lichtkurven (Calaphot)"
    set calaphot(texte,titre_saisie)        "Skript Photomessung Parametern"
    set calaphot(texte,operateur)           "Bedienungsperson Namen"
    set calaphot(texte,objet)               "Objekt Namen"
    set calaphot(texte,code_UAI)            "Sternwarte UAI Kode"
    set calaphot(texte,source)              "Gattungsnamen der Bilder"
    set calaphot(texte,indice_premier)      "Erste Bild Index"
    set calaphot(texte,nombre_images)       "!!!Number of images"
    set calaphot(texte,o_rayon1)            "Innerkreis Halbmesser (in FWHM Zahl)"
    set calaphot(texte,o_rayon2)            "Zentralkreis Halbmesser (in FWHM Zahl)"
    set calaphot(texte,o_rayon3)            "Außerkreis Halbmesser (in FWHM Zahl)"
    set calaphot(texte,sortie)              "Namen der Erfolg Text Datei"
    set calaphot(texte,signal_bruit)        "S/R Verhältnis Grenze"
    set calaphot(texte,mode)                "Rechnung Modus"
    set calaphot(texte,mode_ouverture)      "Öffnung Phot."
    set calaphot(texte,mode_modelisation)   "Sterne Modellierung"
    set calaphot(texte,continuer)           "Weiterführen"
    set calaphot(texte,annuler)             "Annullieren"
    set calaphot(texte,o_surechantillonage) "Rasterpunkte Division Faktor"
    set calaphot(texte,err_indice)          "Irrtum: das letzte Index ist nicht größer als das erste"
    set calaphot(texte,verification)        "Dateien Prüfung von: %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "Die Datei"
    set calaphot(texte,err_existence_2)     "existiert nicht"
    set calaphot(texte,mag_superetoile)     "Größeklasse der Superstern"
    set calaphot(texte,vitesse_asteroide)   "Asteroid Geschwindigkeit (Rastepunkt/Tag)"
    set calaphot(texte,image_rejetee)       "Ausgestoßene Bild"
    set calaphot(texte,etoile)              "Stern"
    set calaphot(texte,asteroide)           "Asteroid"
    set calaphot(texte,moyenne)             "Mittelwert"
    set calaphot(texte,ecart_type)          "Typische Abweichung"
    set calaphot(texte,type_images)         "Bilder Ausführung"
    set calaphot(texte,type_images_0)       "Nicht getrimmt"
    set calaphot(texte,type_images_1)       "Getrimmt"
    set calaphot(texte,format_sortie)       "Daten Format"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopus"
    set calaphot(texte,affichage)           "Rechnungen anzeigen"
    set calaphot(texte,affichage_0)         "Minimal"
    set calaphot(texte,affichage_1)         "Normal"
    set calaphot(texte,affichage_2)         "Maximal"
    set calaphot(texte,date_images)         "Bilder Datum"
    set calaphot(texte,date_images_0)       "Beleuchtung Anfang"
    set calaphot(texte,date_images_1)       "Beleuchtung Mitte"
    set calaphot(texte,param_ouverture)     "Parametern für den Öffnung Modus"
    set calaphot(texte,param_modelisation)  "Parametern für den Modellierung Modus"
    set calaphot(texte,param_generaux)      "Allgemeine Parametern"
    set calaphot(texte,recapitulation)      "Parametern Zusammenfassung"
    set calaphot(texte,heure_debut)         "Anfang um:"
    set calaphot(texte,heure_fin)           "Ende um:"
    set calaphot(texte,fin_normale)         "----------Skript Normale Ende----------"
    set calaphot(texte,fin_anticipee)       "---------Skript Vorzeitige Ende---------"
    set calaphot(texte,validation_etoile)   "Einen Stern hinzufügen"
    set calaphot(texte,devalidation_etoile) "Einen Stern abholen"
    set calaphot(texte,continuation)        "Skript Fortsetzung"
    set calaphot(texte,annulation)          "Skript halten"
    set calaphot(texte,etoile_reference)    "Bezugsstern"
    set calaphot(texte,etoile_a_supprimer)  "Stern zu LOSCHEN"
    set calaphot(texte,magnitude)           "Größeklasse"
    set calaphot(texte,valider)             "Entwerten"
    set calaphot(texte,pas_etoile)          "Sie haben keinen Bezugssternen gewählt!!"
    set calaphot(texte,pas_asteroide)       "Sie haben keinen Asteroid auf die zwei Bildern gewählt!!"
    set calaphot(texte,probleme)            "Problem"
    set calaphot(texte,pos_aster_1)         "Stel. in das erste Bild"
    set calaphot(texte,pos_aster_2)         "Stel. in das letzte Bild"
    set calaphot(texte,etoile_inconnue)     "Unbekannten Stern"
    set calaphot(texte,etoile_prise)        "Schon gewähltes Stern"
    set calaphot(texte,retour)              "Rückkehr"
    set calaphot(texte,calcul_ellipses)     "Von dem Stern Profil Ellipsen Rechnung"
    set calaphot(texte,banniere_CDR_1)      "Daten mit CalaPhot unter"
    set calaphot(texte,banniere_CDR_2)      "AudeLA behandelt"
    set calaphot(texte,et_indesirables)     "Stern zu löschen"
    set calaphot(texte,pose_minute)         "Beleuchtungs Zeit in"
    set calaphot(texte,pose_minute_0)       "Sekunden"
    set calaphot(texte,pose_minute_1)       "Minuten"
    set calaphot(texte,constante_mag)       "Grôsseklasse Konst."
    set calaphot(texte,mauvaise_version)    "Schlechte ligjm Handel Version"
    set calaphot(texte,jour_julien)         "Julian Tag"
    set calaphot(texte,gain_camera)         "Kamera Zunahme (e-/Kodierer Schritt)"
    set calaphot(texte,pas_etoile_ind)      "Keinen Stern zu löschen"
    set calaphot(texte,bruit_lecture)       "Abtastung Rauschen (e-)"
    set calaphot(texte,arret)               "Halten"
    set calaphot(texte,fichier_cl)          "Namen des Erfolg Postscript Datei"
    set calaphot(texte,rien_a_voir)         "Keine Lichtkurve zu zeigen"
    set calaphot(texte,tri_images)          "Mit steigend Datum Bilder Aussortierung"
    set calaphot(texte,type_capteur)        "CCD Typ"
    set calaphot(texte,type_telescope)      "Teleskop Typ"
    set calaphot(texte,diametre_telescope)  "Teleskop Durchmesser (m)"
    set calaphot(texte,focale_telescope)    "Teleskop Focal Länge (m)"
    set calaphot(texte,catalogue_reference) "Referenz Katalog"
    set calaphot(texte,champ1)              "Der Feld "
    set calaphot(texte,champ2)              " soll auch gegeben sein"
    set calaphot(texte,filtre_optique)      "Optischen Filter"
    set calaphot(texte,suivant)             "Nächsten"
    set calaphot(texte,s_saturation)        "Sättigung Höhe (in ADU)"
    set calaphot(texte,mode_sextractor)     "Mit Sextractor"
    set calaphot(texte,non)                 "Nein"
    set calaphot(texte,oui)                 "Ja"
    set calaphot(texte,reprise_astres)      "Mit dem vorherigen ausgewählten Objekt"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Einstellungen für den Sextractor Modus"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "Calaphot Version Änderung: Der calaphot.ini Inhalt wird neu initialisiert."
    set calaphot(texte,aide)                "Hilfe"
    set calaphot(texte,pas_image_valide)    "Kein Bild ist gültig. Überprüfen Sie die S/N Grenze."
    set calaphot(texte,image)               "Bild"
    set calaphot(texte,temps_pose_nul)      "Null Erleuchtung Zeit"
    set calaphot(texte,mag_relative)        "Relative Größe"
    set calaphot(texte,err_modelisation)    "Ausführung Fehler"
    set calaphot(texte,plus_jeune)          " ist älter als die vorherige"
    set calaphot(texte,implication_defoc)   "Die Verarbeitung von sehr unscharf Bilder ist nur mit Blendenöffnung Photometrie möglich."
    set calaphot(texte,defocalisation)      "Sehr unscharf Bilder"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Kein Bild ist gültig"
    set calaphot(texte,niveau_minimal)          "####Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "####Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "###The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "###Image list : "
    set calaphot(texte,liste_vide)              "###No image named as "
    set calaphot(texte,trop_peu_image_2)        "###The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "###Do you to continue ?"
    set calaphot(texte,nombre_variables)        "###Number of variable stars"
    set calaphot(texte,variable)                "###Variable"
    set calaphot(texte,nombre_references)       "###Number of reference stars"
    set calaphot(texte,reference)               "###Reference"
    set calaphot(texte,reference_sans_accent)   "###Reference"
    set calaphot(texte,nom_gardes_faible)       "###Too few selected images"
    set calaphot(texte,titre_selection_finale)  "###Selection of images"
    set calaphot(texte,etape)                   "###Erreur at step "

# *************** Version portugaise **************************
} elseif { [ string compare $langage "portuguese" ] == "0" } {

    set calaphot(texte,titre_menu)          "Curvas de luz (Calaphot)"
    set calaphot(texte,titre_saisie)        "Parâmetros do script de fotometria"
    set calaphot(texte,operateur)           "Nome do operador"
    set calaphot(texte,objet)               "Nome do objecto"
    set calaphot(texte,code_UAI)            "Código UAI do observatório"
    set calaphot(texte,source)              "Nome genérico das imagens"
    set calaphot(texte,indice_premier)      "Índice da primeira imagem"
    set calaphot(texte,nombre_images)       "!!!Number of images"
    set calaphot(texte,o_rayon1)            "Raio do círculo interior (em FWHM)"
    set calaphot(texte,o_rayon2)            "Raio do círculo central (em FWHM)"
    set calaphot(texte,o_rayon3)            "Raio do círculo exterior (em FWHM)"
    set calaphot(texte,sortie)              "Nome do ficheiro texto resultante"
    set calaphot(texte,signal_bruit)        "Relação S/B limite"
    set calaphot(texte,mode)                "Modo de cálculo"
    set calaphot(texte,mode_ouverture)      "Fot. de abertura"
    set calaphot(texte,mode_modelisation)   "Modelização de estrelas"
    set calaphot(texte,continuer)           "Continuar"
    set calaphot(texte,annuler)             "Anular"
    set calaphot(texte,o_surechantillonage) "Factor de divisão de pixeis"
    set calaphot(texte,err_indice)          "Erro: último índice inferior ou igual ao primeiro"
    set calaphot(texte,verification)        "Verificação dos ficheiros %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "O ficheiro"
    set calaphot(texte,err_existence_2)     "não existe"
    set calaphot(texte,mag_superetoile)     "Magnitude da super-estrela"
    set calaphot(texte,vitesse_asteroide)   "Velocidade do asteróide (pixel/dia)"
    set calaphot(texte,image_rejetee)       "Imagem rejeitada"
    set calaphot(texte,etoile)              "Estrela"
    set calaphot(texte,asteroide)           "Asteróide"
    set calaphot(texte,moyenne)             "Média"
    set calaphot(texte,ecart_type)          "Tipo de desvio"
    set calaphot(texte,type_images)         "Tipo de imagens"
    set calaphot(texte,type_images_0)       "Não reajustados"
    set calaphot(texte,type_images_1)       "Reajustados"
    set calaphot(texte,format_sortie)       "Formato dos dados"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopus"
    set calaphot(texte,affichage)           "Afixagem dos cálculos"
    set calaphot(texte,affichage_0)         "Mínima"
    set calaphot(texte,affichage_1)         "Normal"
    set calaphot(texte,affichage_2)         "Máxima"
    set calaphot(texte,date_images)         "Data das imagens"
    set calaphot(texte,date_images_0)       "Início de exposição"
    set calaphot(texte,date_images_1)       "Meio da exposição"
    set calaphot(texte,param_ouverture)     "Parâmetros para o modo abertura"
    set calaphot(texte,param_modelisation)  "Parâmetros para o modo modelização"
    set calaphot(texte,param_generaux)      "Parâmetros gerais"
    set calaphot(texte,recapitulation)      "Recapitulação dos parâmetros"
    set calaphot(texte,heure_debut)         "Início em:"
    set calaphot(texte,heure_fin)           "Fim em:"
    set calaphot(texte,fin_normale)         "----------Fim normal du script-----------"
    set calaphot(texte,fin_anticipee)       "--------Fim antecipado do script---------"
    set calaphot(texte,validation_etoile)   "Acrescentar uma estrela"
    set calaphot(texte,devalidation_etoile) "Retirar uma estrela"
    set calaphot(texte,continuation)        "Continuar no script"
    set calaphot(texte,annulation)          "Parar o script"
    set calaphot(texte,etoile_reference)    "Estrela de referência"
    set calaphot(texte,etoile_a_supprimer)  "Estrela a SUPRIMIR"
    set calaphot(texte,magnitude)           "Magnitude"
    set calaphot(texte,valider)             "Validar"
    set calaphot(texte,pas_etoile)          "Não seleccionou estrelas de referência!!"
    set calaphot(texte,pas_asteroide)       "Não seleccionou o asteróide nas duas imagens!!"
    set calaphot(texte,probleme)            "Problema"
    set calaphot(texte,pos_aster_1)         "Pos. na primeira imagem"
    set calaphot(texte,pos_aster_2)         "Pos. na última imagem"
    set calaphot(texte,etoile_inconnue)     "Estrela desconhecida"
    set calaphot(texte,etoile_prise)        "Estrela já seleccionada"
    set calaphot(texte,retour)              "Voltar"
    set calaphot(texte,calcul_ellipses)     "Cálculo das elipses a partir do perfil da estrela"
    set calaphot(texte,banniere_CDR_1)      "Dados tratados por CalaPhot"
    set calaphot(texte,banniere_CDR_2)      "sob AudeLA"
    set calaphot(texte,et_indesirables)     "Estrelas a suprimir"
    set calaphot(texte,pose_minute)         "Duração da exposição em"
    set calaphot(texte,pose_minute_0)       "Segundos"
    set calaphot(texte,pose_minute_1)       "Minutos"
    set calaphot(texte,constante_mag)       "Const. magnitudes"
    set calaphot(texte,mauvaise_version)    "Incorrecta versão da biblioteca libjm"
    set calaphot(texte,jour_julien)         "Dia Juliano"
    set calaphot(texte,gain_camera)         "Ganho da câmara (e-/passo codificador)"
    set calaphot(texte,pas_etoile_ind)      "Não existe estrela a suprimir"
    set calaphot(texte,bruit_lecture)       "Ruído de leitura (e-)"
    set calaphot(texte,arret)               "Parar"
    set calaphot(texte,fichier_cl)          "Nome do ficheiro PostScript resultante"
    set calaphot(texte,rien_a_voir)         "Não existe curva de brilho para expôr"
    set calaphot(texte,tri_images)          "Triagem de imagens por data crescente"
    set calaphot(texte,type_capteur)        "Tipo de captor"
    set calaphot(texte,type_telescope)      "Tipo de telescópio"
    set calaphot(texte,diametre_telescope)  "Diâmetro do telescópio (m)"
    set calaphot(texte,focale_telescope)    "Focal do telescópio (m)"
    set calaphot(texte,catalogue_reference) "Catálogo de referência"
    set calaphot(texte,champ1)              "O campo "
    set calaphot(texte,champ2)              " deve ser seleccionado"
    set calaphot(texte,filtre_optique)      "Filtro óptico"
    set calaphot(texte,suivant)             "Seguinte"
    set calaphot(texte,s_saturation)        "Nível de saturação (ADU)"
    set calaphot(texte,mode_sextractor)     "Via Sextractor"
    set calaphot(texte,non)                 "Não"
    set calaphot(texte,oui)                 "Sim"
    set calaphot(texte,reprise_astres)      "Retoma de objectos já seleccionados"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Parâmetros para o modo Sextractor"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "Alteração de versão Calaphot: o conteúdo de calaphot.ini será reiniciado."
    set calaphot(texte,aide)                "Ajuda"
    set calaphot(texte,pas_image_valide)    "Nenhuma imagem válida. Verifique o limite de SNR."
    set calaphot(texte,image)               "Imagem"
    set calaphot(texte,temps_pose_nul)      "Tempo de exposição nulo"
    set calaphot(texte,mag_relative)        "Magnitude relativa"
    set calaphot(texte,err_modelisation)    "Erro de modelização"
    set calaphot(texte,plus_jeune)          " é mais antiga do que a anterior"
    set calaphot(texte,implication_defoc)   "O tratamento de imagens muito desfucadas apenas é possível em fotometria de abertura."
    set calaphot(texte,defocalisation)      "Imagens muito desfocadas"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Nenhuma imagem é válida"
    set calaphot(texte,niveau_minimal)          "####Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "####Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "###The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "###Image list : "
    set calaphot(texte,liste_vide)              "###No image named as "
    set calaphot(texte,trop_peu_image_2)        "###The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "###Do you to continue ?"
    set calaphot(texte,nombre_variables)        "###Number of variable stars"
    set calaphot(texte,variable)                "###Variable"
    set calaphot(texte,nombre_references)       "###Number of reference stars"
    set calaphot(texte,reference)               "###Reference"
    set calaphot(texte,reference_sans_accent)   "###Reference"
    set calaphot(texte,nom_gardes_faible)       "###Too few selected images"
    set calaphot(texte,titre_selection_finale)  "###Selection of images"
    set calaphot(texte,etape)                   "###Erreur at step "

# *************** Version danoise *****************************
} elseif { [ string compare $langage "danish" ] == "0" } {

    set calaphot(texte,titre_menu)          "Light Curves (Calaphot)"
    set calaphot(texte,titre_saisie)        "Photometry Script Parameters"
    set calaphot(texte,operateur)           "Operator Name"
    set calaphot(texte,objet)               "Object Name"
    set calaphot(texte,code_UAI)            "Observatory IUA Code"
    set calaphot(texte,source)              "Generic Name for the Image Files"
    set calaphot(texte,indice_premier)      "First Image Index"
    set calaphot(texte,nombre_images)       "!!!Number of images"
    set calaphot(texte,o_rayon1)            "Inner Oval Radius (in FWHM)"
    set calaphot(texte,o_rayon2)            "Inner Crown Radius (in FWHM)"
    set calaphot(texte,o_rayon3)            "Outer Crown Radius (in FWHM)"
    set calaphot(texte,sortie)              "Output Generic File Name"
    set calaphot(texte,signal_bruit)        "Minimum S/N Ratio"
    set calaphot(texte,mode)                "Calculation Mode"
    set calaphot(texte,mode_ouverture)      "Aperture Photometry"
    set calaphot(texte,mode_modelisation)   "Star Modelling"
    set calaphot(texte,continuer)           "Go"
    set calaphot(texte,annuler)             "Cancel"
    set calaphot(texte,o_surechantillonage) "Pixel Oversampling"
    set calaphot(texte,err_indice)          "Error:  last index is smaller or equal to the first one"
    set calaphot(texte,verification)        "Check Files %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "The file"
    set calaphot(texte,err_existence_2)     "does not exist"
    set calaphot(texte,mag_superetoile)     "Magnitude of the Super Star"
    set calaphot(texte,vitesse_asteroide)   "Asteroid Speed (pixel/day)"
    set calaphot(texte,image_rejetee)       "Rejected Image"
    set calaphot(texte,etoile)              "Star"
    set calaphot(texte,asteroide)           "Asteroid"
    set calaphot(texte,moyenne)             "Average"
    set calaphot(texte,ecart_type)          "Standard Deviation"
    set calaphot(texte,type_images)         "Image Type"
    set calaphot(texte,type_images_0)       "Not Registered"
    set calaphot(texte,type_images_1)       "Registered"
    set calaphot(texte,format_sortie)       "Data Format"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopus"
    set calaphot(texte,affichage)           "Calculation Display"
    set calaphot(texte,affichage_0)         "Minimum"
    set calaphot(texte,affichage_1)         "Normal"
    set calaphot(texte,affichage_2)         "Maximum"
    set calaphot(texte,date_images)         "Image Date"
    set calaphot(texte,date_images_0)       "Start of Exposure"
    set calaphot(texte,date_images_1)       "Center of Exposure"
    set calaphot(texte,param_ouverture)     "Parameters for the Aperture Mode"
    set calaphot(texte,param_modelisation)  "Parameters for the Modelling Mode"
    set calaphot(texte,param_generaux)      "General Settings"
    set calaphot(texte,recapitulation)      "Summary"
    set calaphot(texte,heure_debut)         "Start at:"
    set calaphot(texte,heure_fin)           "End at:"
    set calaphot(texte,fin_normale)         "----------Normal End of Script----------"
    set calaphot(texte,fin_anticipee)       "----------Abnormal End of Script---------"
    set calaphot(texte,validation_etoile)   "Adding a Star"
    set calaphot(texte,devalidation_etoile) "Removing a Star"
    set calaphot(texte,continuation)        "Next"
    set calaphot(texte,annulation)          "Stop"
    set calaphot(texte,etoile_reference)    "Reference Star"
    set calaphot(texte,etoile_a_supprimer)  "Star to REMOVE"
    set calaphot(texte,magnitude)           "Magnitude"
    set calaphot(texte,valider)             "OK"
    set calaphot(texte,pas_etoile)          "No reference star selected!"
    set calaphot(texte,pas_asteroide)       "No asteroid selected on both images!"
    set calaphot(texte,probleme)            "Problem"
    set calaphot(texte,pos_aster_1)         "Pos. in First Image"
    set calaphot(texte,pos_aster_2)         "Pos. in Last Image"
    set calaphot(texte,etoile_inconnue)     "Unknown Star"
    set calaphot(texte,etoile_prise)        "Star Alrealy Selected"
    set calaphot(texte,retour)              "Back"
    set calaphot(texte,calcul_ellipses)     "Ellipse Calculation from Star Profile"
    set calaphot(texte,banniere_CDR_1)      "Data Processed by CalaPhot"
    set calaphot(texte,banniere_CDR_2)      "under AudeLA"
    set calaphot(texte,et_indesirables)     "Star to Remove"
    set calaphot(texte,pose_minute)         "Exposure Duration in"
    set calaphot(texte,pose_minute_0)       "Seconds"
    set calaphot(texte,pose_minute_1)       "Minutes"
    set calaphot(texte,constante_mag)       "Magnitudes Const."
    set calaphot(texte,mauvaise_version)    "Bad Version of libjm Library"
    set calaphot(texte,jour_julien)         "Julian Day"
    set calaphot(texte,gain_camera)         "Camera Gain (e-/ADU)"
    set calaphot(texte,pas_etoile_ind)      "No Star to Remove"
    set calaphot(texte,bruit_lecture)       "Readout Noise (e-)"
    set calaphot(texte,arret)               "Stop"
    set calaphot(texte,fichier_cl)          "Name of Resulting PostScript File"
    set calaphot(texte,rien_a_voir)         "No Light Curve"
    set calaphot(texte,tri_images)          "Sorting by Date of Images"
    set calaphot(texte,type_capteur)        "CCD Model"
    set calaphot(texte,type_telescope)      "Telescope Type"
    set calaphot(texte,diametre_telescope)  "Telescope Aperture (m)"
    set calaphot(texte,focale_telescope)    "Telescope Focal Length (m)"
    set calaphot(texte,catalogue_reference) "Reference Catalog"
    set calaphot(texte,champ1)              "The field "
    set calaphot(texte,champ2)              " must contain a value"
    set calaphot(texte,filtre_optique)      "Optical Filter"
    set calaphot(texte,suivant)             "Next"
    set calaphot(texte,s_saturation)        "Saturation level (ADU)"
    set calaphot(texte,mode_sextractor)     "Using Sextractor"
    set calaphot(texte,non)                 "No"
    set calaphot(texte,oui)                 "Yes"
    set calaphot(texte,reprise_astres)      "Using the previously selected objects"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Parameters for the Sextractor Mode"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "The Calaphot version has changed: The calaphot.ini settings will be reset."
    set calaphot(texte,aide)                "Help"
    set calaphot(texte,pas_image_valide)    "No valid image. You should check the minimum S/N ratio."
    set calaphot(texte,image)               "Image"
    set calaphot(texte,temps_pose_nul)      "Void exposure duration"
    set calaphot(texte,mag_relative)        "Relative Magnitude"
    set calaphot(texte,err_modelisation)    "Error in fitting"
    set calaphot(texte,plus_jeune)          " is older than the previous one"
    set calaphot(texte,implication_defoc)   "The processing of very defocused images implies Aperture Photometry."
    set calaphot(texte,defocalisation)      "Very defocused images"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Not any valid image"
    set calaphot(texte,niveau_minimal)          "Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "Image list : "
    set calaphot(texte,liste_vide)              "No image named as "
    set calaphot(texte,trop_peu_image_2)        "The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "Do you to continue ?"
    set calaphot(texte,nombre_variables)        "Number of variable stars"
    set calaphot(texte,variable)                "Variable"
    set calaphot(texte,nombre_references)       "Number of reference stars"
    set calaphot(texte,reference)               "Reference"
    set calaphot(texte,reference_sans_accent)   "Reference"
    set calaphot(texte,nom_gardes_faible)       "Too few selected images"
    set calaphot(texte,titre_selection_finale)  "Selection of images"
    set calaphot(texte,etape)                   "Erreur at step "

# *************** Version ukrainienne *************************
} elseif { [ string compare $langage "ukrainian" ] == "0" } {

    set calaphot(texte,titre_menu)          "Light Curves (Calaphot)"
    set calaphot(texte,titre_saisie)        "Photometry Script Parameters"
    set calaphot(texte,operateur)           "Operator Name"
    set calaphot(texte,objet)               "Object Name"
    set calaphot(texte,code_UAI)            "Observatory IUA Code"
    set calaphot(texte,source)              "Generic Name for the Image Files"
    set calaphot(texte,indice_premier)      "First Image Index"
    set calaphot(texte,nombre_images)       "!!!Number of images"
    set calaphot(texte,o_rayon1)            "Inner Oval Radius (in FWHM)"
    set calaphot(texte,o_rayon2)            "Inner Crown Radius (in FWHM)"
    set calaphot(texte,o_rayon3)            "Outer Crown Radius (in FWHM)"
    set calaphot(texte,sortie)              "Output Generic File Name"
    set calaphot(texte,signal_bruit)        "Minimum S/N Ratio"
    set calaphot(texte,mode)                "Calculation Mode"
    set calaphot(texte,mode_ouverture)      "Aperture Photometry"
    set calaphot(texte,mode_modelisation)   "Star Modelling"
    set calaphot(texte,continuer)           "Go"
    set calaphot(texte,annuler)             "Cancel"
    set calaphot(texte,o_surechantillonage) "Pixel Oversampling"
    set calaphot(texte,err_indice)          "Error:  last index is smaller or equal to the first one"
    set calaphot(texte,verification)        "Check Files %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "The file"
    set calaphot(texte,err_existence_2)     "does not exist"
    set calaphot(texte,mag_superetoile)     "Magnitude of the Super Star"
    set calaphot(texte,vitesse_asteroide)   "Asteroid Speed (pixel/day)"
    set calaphot(texte,image_rejetee)       "Rejected Image"
    set calaphot(texte,etoile)              "Star"
    set calaphot(texte,asteroide)           "Asteroid"
    set calaphot(texte,moyenne)             "Average"
    set calaphot(texte,ecart_type)          "Standard Deviation"
    set calaphot(texte,type_images)         "Image Type"
    set calaphot(texte,type_images_0)       "Not Registered"
    set calaphot(texte,type_images_1)       "Registered"
    set calaphot(texte,format_sortie)       "Data Format"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopus"
    set calaphot(texte,affichage)           "Calculation Display"
    set calaphot(texte,affichage_0)         "Minimum"
    set calaphot(texte,affichage_1)         "Normal"
    set calaphot(texte,affichage_2)         "Maximum"
    set calaphot(texte,date_images)         "Image Date"
    set calaphot(texte,date_images_0)       "Start of Exposure"
    set calaphot(texte,date_images_1)       "Center of Exposure"
    set calaphot(texte,param_ouverture)     "Parameters for the Aperture Mode"
    set calaphot(texte,param_modelisation)  "Parameters for the Modelling Mode"
    set calaphot(texte,param_generaux)      "General Settings"
    set calaphot(texte,recapitulation)      "Summary"
    set calaphot(texte,heure_debut)         "Start at:"
    set calaphot(texte,heure_fin)           "End at:"
    set calaphot(texte,fin_normale)         "----------Normal End of Script----------"
    set calaphot(texte,fin_anticipee)       "----------Abnormal End of Script---------"
    set calaphot(texte,validation_etoile)   "Adding a Star"
    set calaphot(texte,devalidation_etoile) "Removing a Star"
    set calaphot(texte,continuation)        "Next"
    set calaphot(texte,annulation)          "Stop"
    set calaphot(texte,etoile_reference)    "Reference Star"
    set calaphot(texte,etoile_a_supprimer)  "Star to REMOVE"
    set calaphot(texte,magnitude)           "Magnitude"
    set calaphot(texte,valider)             "OK"
    set calaphot(texte,pas_etoile)          "No reference star selected!"
    set calaphot(texte,pas_asteroide)       "No asteroid selected on both images!"
    set calaphot(texte,probleme)            "Problem"
    set calaphot(texte,pos_aster_1)         "Pos. in First Image"
    set calaphot(texte,pos_aster_2)         "Pos. in Last Image"
    set calaphot(texte,etoile_inconnue)     "Unknown Star"
    set calaphot(texte,etoile_prise)        "Star Alrealy Selected"
    set calaphot(texte,retour)              "Back"
    set calaphot(texte,calcul_ellipses)     "Ellipse Calculation from Star Profile"
    set calaphot(texte,banniere_CDR_1)      "Data Processed by CalaPhot"
    set calaphot(texte,banniere_CDR_2)      "under AudeLA"
    set calaphot(texte,et_indesirables)     "Star to Remove"
    set calaphot(texte,pose_minute)         "Exposure Duration in"
    set calaphot(texte,pose_minute_0)       "Seconds"
    set calaphot(texte,pose_minute_1)       "Minutes"
    set calaphot(texte,constante_mag)       "Magnitudes Const."
    set calaphot(texte,mauvaise_version)    "Bad Version of libjm Library"
    set calaphot(texte,jour_julien)         "Julian Day"
    set calaphot(texte,gain_camera)         "Camera Gain (e-/ADU)"
    set calaphot(texte,pas_etoile_ind)      "No Star to Remove"
    set calaphot(texte,bruit_lecture)       "Readout Noise (e-)"
    set calaphot(texte,arret)               "Stop"
    set calaphot(texte,fichier_cl)          "Name of Resulting PostScript File"
    set calaphot(texte,rien_a_voir)         "No Light Curve"
    set calaphot(texte,tri_images)          "Sorting by Date of Images"
    set calaphot(texte,type_capteur)        "CCD Model"
    set calaphot(texte,type_telescope)      "Telescope Type"
    set calaphot(texte,diametre_telescope)  "Telescope Aperture (m)"
    set calaphot(texte,focale_telescope)    "Telescope Focal Length (m)"
    set calaphot(texte,catalogue_reference) "Reference Catalog"
    set calaphot(texte,champ1)              "The field "
    set calaphot(texte,champ2)              " must contain a value"
    set calaphot(texte,filtre_optique)      "Optical Filter"
    set calaphot(texte,suivant)             "Next"
    set calaphot(texte,s_saturation)        "Saturation level (ADU)"
    set calaphot(texte,mode_sextractor)     "Using Sextractor"
    set calaphot(texte,reprise_astres)      "Using the previously selected objects"
    set calaphot(texte,non)                 "No"
    set calaphot(texte,oui)                 "Yes"
    set calaphot(texte,reprise_astres)      "Using the previously selected objects"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Parameters for the Sextractor Mode"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "The Calaphot version has changed: The calaphot.ini settings will be reset."
    set calaphot(texte,aide)                "Help"
    set calaphot(texte,pas_image_valide)    "No valid image. You should check the minimum S/N ratio."
    set calaphot(texte,image)               "Image"
    set calaphot(texte,temps_pose_nul)      "Void exposure duration"
    set calaphot(texte,mag_relative)        "Relative Magnitude"
    set calaphot(texte,err_modelisation)    "Error in fitting"
    set calaphot(texte,plus_jeune)          " is older than the previous one"
    set calaphot(texte,implication_defoc)   "The processing of very defocused images implies Aperture Photometry."
    set calaphot(texte,defocalisation)      "Very defocused images"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Not any valid image"
    set calaphot(texte,niveau_minimal)          "Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "Image list : "
    set calaphot(texte,liste_vide)              "No image named as "
    set calaphot(texte,trop_peu_image_2)        "The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "Do you to continue ?"
    set calaphot(texte,nombre_variables)        "Number of variable stars"
    set calaphot(texte,variable)                "Variable"
    set calaphot(texte,nombre_references)       "Number of reference stars"
    set calaphot(texte,reference)               "Reference"
    set calaphot(texte,reference_sans_accent)   "Reference"
    set calaphot(texte,nom_gardes_faible)       "Too few selected images"
    set calaphot(texte,titre_selection_finale)  "Selection of images"
    set calaphot(texte,etape)                   "Erreur at step "

# *************** Version russe *******************************
} elseif { [ string compare $langage "russian" ] == "0" } {

    set calaphot(texte,titre_menu)          "Light Curves (Calaphot)"
    set calaphot(texte,titre_saisie)        "Photometry Script Parameters"
    set calaphot(texte,operateur)           "Operator Name"
    set calaphot(texte,objet)               "Object Name"
    set calaphot(texte,code_UAI)            "Observatory IUA Code"
    set calaphot(texte,source)              "Generic Name for the Image Files"
    set calaphot(texte,indice_premier)      "First Image Index"
    set calaphot(texte,nombre_images)       "!!!Number of images"
    set calaphot(texte,o_rayon1)            "Inner Oval Radius (in FWHM)"
    set calaphot(texte,o_rayon2)            "Inner Crown Radius (in FWHM)"
    set calaphot(texte,o_rayon3)            "Outer Crown Radius (in FWHM)"
    set calaphot(texte,sortie)              "Output Generic File Name"
    set calaphot(texte,signal_bruit)        "Minimum S/N Ratio"
    set calaphot(texte,mode)                "Calculation Mode"
    set calaphot(texte,mode_ouverture)      "Aperture Photometry"
    set calaphot(texte,mode_modelisation)   "Star Modelling"
    set calaphot(texte,continuer)           "Go"
    set calaphot(texte,annuler)             "Cancel"
    set calaphot(texte,o_surechantillonage) "Pixel Oversampling"
    set calaphot(texte,err_indice)          "Error:  last index is smaller or equal to the first one"
    set calaphot(texte,verification)        "Check Files %s\[%d...%d\]%s"
    set calaphot(texte,err_existence_1)     "The file"
    set calaphot(texte,err_existence_2)     "does not exist"
    set calaphot(texte,mag_superetoile)     "Magnitude of the Super Star"
    set calaphot(texte,vitesse_asteroide)   "Asteroid Speed (pixel/day)"
    set calaphot(texte,image_rejetee)       "Rejected Image"
    set calaphot(texte,etoile)              "Star"
    set calaphot(texte,asteroide)           "Asteroid"
    set calaphot(texte,moyenne)             "Average"
    set calaphot(texte,ecart_type)          "Standard Deviation"
    set calaphot(texte,type_images)         "Image Type"
    set calaphot(texte,type_images_0)       "Not Registered"
    set calaphot(texte,type_images_1)       "Registered"
    set calaphot(texte,format_sortie)       "Data Format"
    set calaphot(texte,format_sortie_0)     "CDR"
    set calaphot(texte,format_sortie_1)     "Canopus"
    set calaphot(texte,affichage)           "Calculation Display"
    set calaphot(texte,affichage_0)         "Minimum"
    set calaphot(texte,affichage_1)         "Normal"
    set calaphot(texte,affichage_2)         "Maximum"
    set calaphot(texte,date_images)         "Image Date"
    set calaphot(texte,date_images_0)       "Start of Exposure"
    set calaphot(texte,date_images_1)       "Center of Exposure"
    set calaphot(texte,param_ouverture)     "Parameters for the Aperture Mode"
    set calaphot(texte,param_modelisation)  "Parameters for the Modelling Mode"
    set calaphot(texte,param_generaux)      "General Settings"
    set calaphot(texte,recapitulation)      "Summary"
    set calaphot(texte,heure_debut)         "Start at:"
    set calaphot(texte,heure_fin)           "End at:"
    set calaphot(texte,fin_normale)         "----------Normal End of Script----------"
    set calaphot(texte,fin_anticipee)       "----------Abnormal End of Script---------"
    set calaphot(texte,validation_etoile)   "Adding a Star"
    set calaphot(texte,devalidation_etoile) "Removing a Star"
    set calaphot(texte,continuation)        "Next"
    set calaphot(texte,annulation)          "Stop"
    set calaphot(texte,etoile_reference)    "Reference Star"
    set calaphot(texte,etoile_a_supprimer)  "Star to REMOVE"
    set calaphot(texte,magnitude)           "Magnitude"
    set calaphot(texte,valider)             "OK"
    set calaphot(texte,pas_etoile)          "No reference star selected!"
    set calaphot(texte,pas_asteroide)       "No asteroid selected on both images!"
    set calaphot(texte,probleme)            "Problem"
    set calaphot(texte,pos_aster_1)         "Pos. in First Image"
    set calaphot(texte,pos_aster_2)         "Pos. in Last Image"
    set calaphot(texte,etoile_inconnue)     "Unknown Star"
    set calaphot(texte,etoile_prise)        "Star Alrealy Selected"
    set calaphot(texte,retour)              "Back"
    set calaphot(texte,calcul_ellipses)     "Ellipse Calculation from Star Profile"
    set calaphot(texte,banniere_CDR_1)      "Data Processed by CalaPhot"
    set calaphot(texte,banniere_CDR_2)      "under AudeLA"
    set calaphot(texte,et_indesirables)     "Star to Remove"
    set calaphot(texte,pose_minute)         "Exposure Duration in"
    set calaphot(texte,pose_minute_0)       "Seconds"
    set calaphot(texte,pose_minute_1)       "Minutes"
    set calaphot(texte,constante_mag)       "Magnitudes Const."
    set calaphot(texte,mauvaise_version)    "Bad Version of libjm Library"
    set calaphot(texte,jour_julien)         "Julian Day"
    set calaphot(texte,gain_camera)         "Camera Gain (e-/ADU)"
    set calaphot(texte,pas_etoile_ind)      "No Star to Remove"
    set calaphot(texte,bruit_lecture)       "Readout Noise (e-)"
    set calaphot(texte,arret)               "Stop"
    set calaphot(texte,fichier_cl)          "Name of Resulting PostScript File"
    set calaphot(texte,rien_a_voir)         "No Light Curve"
    set calaphot(texte,tri_images)          "Sorting by Date of Images"
    set calaphot(texte,type_capteur)        "CCD Model"
    set calaphot(texte,type_telescope)      "Telescope Type"
    set calaphot(texte,diametre_telescope)  "Telescope Aperture (m)"
    set calaphot(texte,focale_telescope)    "Telescope Focal Length (m)"
    set calaphot(texte,catalogue_reference) "Reference Catalog"
    set calaphot(texte,champ1)              "The field "
    set calaphot(texte,champ2)              " must contain a value"
    set calaphot(texte,filtre_optique)      "Optical Filter"
    set calaphot(texte,suivant)             "Next"
    set calaphot(texte,s_saturation)        "Saturation level (ADU)"
    set calaphot(texte,mode_sextractor)     "Using Sextractor"
    set calaphot(texte,non)                 "No"
    set calaphot(texte,oui)                 "Yes"
    set calaphot(texte,reprise_astres)      "Using the previously selected objects"
    set calaphot(texte,reprise_astres_0)    $calaphot(texte,non)
    set calaphot(texte,reprise_astres_1)    $calaphot(texte,oui)
    set calaphot(texte,param_sextractor)    "Parameters for the Sextractor Mode"
    set calaphot(texte,tri_images_0)        $calaphot(texte,non)
    set calaphot(texte,tri_images_1)        $calaphot(texte,oui)
    set calaphot(texte,detection_ini)       "The Calaphot version has changed: The calaphot.ini settings will be reset."
    set calaphot(texte,aide)                "Help"
    set calaphot(texte,pas_image_valide)    "No valid image. You should check the minimum S/N ratio."
    set calaphot(texte,image)               "Image"
    set calaphot(texte,temps_pose_nul)      "Void exposure duration"
    set calaphot(texte,mag_relative)        "Relative Magnitude"
    set calaphot(texte,err_modelisation)    "Error in fitting"
    set calaphot(texte,plus_jeune)          " is older than the previous one"
    set calaphot(texte,implication_defoc)   "The processing of very defocused images implies Aperture Photometry."
    set calaphot(texte,defocalisation)      "Very defocused images"
    set calaphot(texte,defocalisation_0)    $calaphot(texte,non)
    set calaphot(texte,defocalisation_1)    $calaphot(texte,oui)
    set calaphot(texte,aucune_valide)       "Not any valid image"
    set calaphot(texte,niveau_minimal)          "Lower Limit for ADU (floor)"
    set calaphot(texte,niveau_maximal)          "Higher Limit for ADU (ceiling)"
    set calaphot(texte,trop_peu_image)          "The number of images to process is smaller than 2"
    set calaphot(texte,liste_image)             "Image list : "
    set calaphot(texte,liste_vide)              "No image named as "
    set calaphot(texte,trop_peu_image_2)        "The number of images to process is smaller than specified"
    set calaphot(texte,question_continuer)      "Do you to continue ?"
    set calaphot(texte,nombre_variables)        "Number of variable stars"
    set calaphot(texte,variable)                "Variable"
    set calaphot(texte,nombre_references)       "Number of reference stars"
    set calaphot(texte,reference)               "Reference"
    set calaphot(texte,reference_sans_accent)   "Reference"
    set calaphot(texte,nom_gardes_faible)       "Too few selected images"
    set calaphot(texte,titre_selection_finale)  "Selection of images"
    set calaphot(texte,etape)                   "Erreur at step "
}

#=========================================================================
#   Fin de la déclaration des textes localisés (internationalisation)
#=========================================================================

