# This file is automatically generated and will be overwritten
namespace eval twapi {
    variable version 2.0
    variable patchlevel 2.0.12
}
# The build_id is generated automatically on every build 
set twapi::build_id 153faff1-1ef7-c44c-ad7e-97e7ee9d1777
