
# This file was automatically generated by TEKI
global tclPkgInfo
if {![info exists tclPkgInfo(installed)] ||
    [lsearch $tclPkgInfo(installed) dp4.0] == -1} {
    lappend tclPkgInfo(installed) dp4.0

    set tclPkgInfo(dp4.0,codePrefix)      {C:/Program Files/TCL/lib/tcl7.6}
    set tclPkgInfo(dp4.0,docPrefix)       {C:/Program Files/TCL/doc}
    set tclPkgInfo(dp4.0,installData)     0
    set tclPkgInfo(dp4.0,installDoc)      0
    set tclPkgInfo(dp4.0,installExamples) 0

    set tclPkgInfo(dp4.0,name)            dp
    set tclPkgInfo(dp4.0,version)         4.0
    set tclPkgInfo(dp4.0,description)     Tcl-DP
    set tclPkgInfo(dp4.0,requires)        {{Tcl 7.6}}
    set tclPkgInfo(dp4.0,tekiFile)        dp.tek
    set tclPkgInfo(dp4.0,updateURL)       {}
    set tclPkgInfo(dp4.0,registerURL)     {}
    set tclPkgInfo(dp4.0,destDir)         dp4.0
    set tclPkgInfo(dp4.0,tclFiles)        {
    #library/acl.tcl library/distribObj.tcl library/dp_atclose.tcl
    library/dp_atexit.tcl library/ldelete.tcl library/oo.tcl library/rpc.tcl
}
    set tclPkgInfo(dp4.0,systemNames)     {
        {Solaris SunOS 5*}
        {SunOS SunOS 4*}
        {HPUX HP* 9*}
        {Linux Linux* 2*}
        {FreeBSD FreeBSD* 2*}
        {Win95/NT Win* *}
}
    set tclPkgInfo(dp4.0,infoFile)        {C:/Program Files/TCL/lib/tcl7.6/dp4.0/README}
    set tclPkgInfo(dp4.0,dataFiles) {}
    set tclPkgInfo(dp4.0,exampleFiles) {}
    set tclPkgInfo(dp4.0,objFiles,Win95/NT) win/dp40.dll
    set tclPkgInfo(dp4.0,archList) Win95/NT
}
package ifneeded dp 4.0 [list dp_LoadLib $dir]

proc dp_LoadLib dir {
    foreach file [glob $dir/library/*.tcl] {
        uplevel #0 source [list $file]
    }
    uplevel #0 load [list $dir/win/dp40.dll]
}
