load libcatalog.so
source [file join $bddconf(astroid) get_cata.tcl      ]
source [file join $bddconf(astroid) visu.tcl          ]
source [file join $bddconf(astroid) get_one_image.tcl ]
source [file join $bddconf(astroid) imprimlist.tcl    ]
source [file join $bddconf(astroid) astrometry.tcl    ]
source [file join $bddconf(astroid) photometry.tcl    ]
source [file join $bddconf(astroid) identification.tcl]
source [file join $bddconf(astroid) manage_source.tcl ]
source [file join $bddconf(astroid) analyse_source.tcl]
source [file join $bddconf(astroid) get_skybot.tcl    ]
source [file join $bddconf(astroid) get_info.tcl      ]
source [file join $bddconf(astroid) votable.tcl       ]
