load libcatalog[info sharedlibextension]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid get_cata.tcl      ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid visu.tcl          ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid get_one_image.tcl ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid imprimlist.tcl    ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid astrometry.tcl    ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid photometry.tcl    ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid identification.tcl]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid manage_source.tcl ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid analyse_source.tcl]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid get_skybot.tcl    ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid get_info.tcl      ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid votable.tcl       ]
#source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid priam.tcl         ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid statbox.tcl       ]
source [file join $audace(rep_install) gui audace plugin tool bddimages utils astroid constantes.tcl    ]
